package mariot7.decorativestyles.init;

import mariot7.decorativestyles.Main;
import mariot7.decorativestyles.Reference;
import mariot7.decorativestyles.blocks.AcaciaWoodParquet;
import mariot7.decorativestyles.blocks.BirchWoodParquet;
import mariot7.decorativestyles.blocks.CarvedStone1;
import mariot7.decorativestyles.blocks.CarvedStone2;
import mariot7.decorativestyles.blocks.CarvedStone3;
import mariot7.decorativestyles.blocks.Cement;
import mariot7.decorativestyles.blocks.CheckedGlass;
import mariot7.decorativestyles.blocks.ClearGlass;
import mariot7.decorativestyles.blocks.Concrete;
import mariot7.decorativestyles.blocks.ConcreteMasonryUnit;
import mariot7.decorativestyles.blocks.ConcreteTiles;
import mariot7.decorativestyles.blocks.DarkMetal;
import mariot7.decorativestyles.blocks.DarkoakWoodParquet;
import mariot7.decorativestyles.blocks.Glass101;
import mariot7.decorativestyles.blocks.JailGlass;
import mariot7.decorativestyles.blocks.JungleBrickBlock;
import mariot7.decorativestyles.blocks.JungleCobblestone;
import mariot7.decorativestyles.blocks.JungleConcreteMasonryUnit;
import mariot7.decorativestyles.blocks.JungleMossyCobblestone;
import mariot7.decorativestyles.blocks.JungleMossyStoneBrick;
import mariot7.decorativestyles.blocks.JunglePolishedStone;
import mariot7.decorativestyles.blocks.JunglePurpurBlock;
import mariot7.decorativestyles.blocks.JungleStone;
import mariot7.decorativestyles.blocks.JungleStoneBrick;
import mariot7.decorativestyles.blocks.JungleStoneBrickCarved;
import mariot7.decorativestyles.blocks.JungleStoneBrickCracked;
import mariot7.decorativestyles.blocks.JungleWoodParquet;
import mariot7.decorativestyles.blocks.OakWoodParquet;
import mariot7.decorativestyles.blocks.PolishedPumice;
import mariot7.decorativestyles.blocks.Pumice;
import mariot7.decorativestyles.blocks.PumiceBrickBlock;
import mariot7.decorativestyles.blocks.PumiceGlass;
import mariot7.decorativestyles.blocks.PumiceMasonryUnit;
import mariot7.decorativestyles.blocks.PumiceMossyStoneBrick;
import mariot7.decorativestyles.blocks.PumicePurpurBlock;
import mariot7.decorativestyles.blocks.PumiceStoneBrick;
import mariot7.decorativestyles.blocks.PumiceStoneBrickCarved;
import mariot7.decorativestyles.blocks.PumiceStoneBrickCracked;
import mariot7.decorativestyles.blocks.QuartzGlass;
import mariot7.decorativestyles.blocks.RustyBlock;
import mariot7.decorativestyles.blocks.SnowBrickBlock;
import mariot7.decorativestyles.blocks.SnowCobblestone;
import mariot7.decorativestyles.blocks.SnowConcreteMasonryUnit;
import mariot7.decorativestyles.blocks.SnowMossyCobblestone;
import mariot7.decorativestyles.blocks.SnowMossyStoneBrick;
import mariot7.decorativestyles.blocks.SnowPolishedStone;
import mariot7.decorativestyles.blocks.SnowPurpurBlock;
import mariot7.decorativestyles.blocks.SnowStone;
import mariot7.decorativestyles.blocks.SnowStoneBrick;
import mariot7.decorativestyles.blocks.SnowStoneBrickCarved;
import mariot7.decorativestyles.blocks.SnowStoneBrickCracked;
import mariot7.decorativestyles.blocks.SpruceWoodParquet;
import mariot7.decorativestyles.blocks.WhiteBrickBlock;
import mariot7.decorativestyles.blocks.WhiteCobblestone;
import mariot7.decorativestyles.blocks.WhiteConcreteMasonryUnit;
import mariot7.decorativestyles.blocks.WhiteMossyCobblestone;
import mariot7.decorativestyles.blocks.WhiteMossyStoneBrick;
import mariot7.decorativestyles.blocks.WhitePolishedStone;
import mariot7.decorativestyles.blocks.WhitePurpurBlock;
import mariot7.decorativestyles.blocks.WhiteStone;
import mariot7.decorativestyles.blocks.WhiteStoneBrick;
import mariot7.decorativestyles.blocks.WhiteStoneBrickCarved;
import mariot7.decorativestyles.blocks.WhiteStoneBrickCracked;
import mariot7.decorativestyles.lore.ItemClearGlass;
import mariot7.decorativestyles.lore.ItemConcreteMasonryUnit;
import mariot7.decorativestyles.lore.ItemGlass101;
import mariot7.decorativestyles.lore.ItemJungleCobblestone;
import mariot7.decorativestyles.lore.ItemJungleConcreteMasonryUnit;
import mariot7.decorativestyles.lore.ItemPumice;
import mariot7.decorativestyles.lore.ItemPumiceMasonryUnit;
import mariot7.decorativestyles.lore.ItemSnowConcreteMasonryUnit;
import mariot7.decorativestyles.lore.ItemWhiteConcreteMasonryUnit;
import mariot7.decorativestyles.lore.ItemWhiteStone;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.item.Item;
import net.minecraftforge.fml.common.registry.GameRegistry;

public class BlockListds {
	
	//concrete blocks
	public static Block cement;
	public static Block concrete;
	public static Block concrete_masonry_unit;
	public static Block concrete_tiles;
	//jungle blocks
	public static Block jungle_cobblestone;
	public static Block jungle_mossy_cobblestone;
	public static Block jungle_stone;
	public static Block jungle_polished_stone;
	public static Block jungle_stonebrick;
    public static Block jungle_mossy_stonebrick;
	public static Block jungle_stonebrick_cracked;
	public static Block jungle_stonebrick_carved;
	public static Block jungle_brick_block;
	public static Block jungle_purpur_block;
	public static Block jungle_concrete_masonry_unit;
	//white blocks
	public static Block white_cobblestone;
	public static Block white_mossy_cobblestone;
	public static Block white_stone;
	public static Block white_polished_stone;
	public static Block white_stonebrick;
	public static Block white_mossy_stonebrick;
	public static Block white_stonebrick_cracked;
	public static Block white_stonebrick_carved;
	public static Block white_brick_block;
	public static Block white_purpur_block;
	public static Block white_concrete_masonry_unit;
	//snow blocks
	public static Block snow_cobblestone;
	public static Block snow_mossy_cobblestone;
	public static Block snow_stone;
	public static Block snow_polished_stone;
	public static Block snow_stonebrick;
	public static Block snow_mossy_stonebrick;
	public static Block snow_stonebrick_cracked;
	public static Block snow_stonebrick_carved;
	public static Block snow_brick_block;
	public static Block snow_purpur_block;
	public static Block snow_concrete_masonry_unit;
	//pumice blocks
	public static Block pumice;
	public static Block polished_pumice;
	public static Block pumice_stonebrick;
	public static Block pumice_mossy_stonebrick;
	public static Block pumice_stonebrick_cracked;
	public static Block pumice_stonebrick_carved;
	public static Block pumice_brick_block;
	public static Block pumice_purpur_block;
	public static Block pumice_masonry_unit;
	//carved stone blocks
	public static Block carved_stone_1;
	public static Block carved_stone_2;
	public static Block carved_stone_3;
	//wooden blocks
	public static Block oak_wood_parquet;
	public static Block birch_wood_parquet;
	public static Block spruce_wood_parquet;
	public static Block jungle_wood_parquet;
	public static Block acacia_wood_parquet;
	public static Block darkoak_wood_parquet;
	//rusty blocks
	public static Block rusty_block;
	//dark metal blocks
	public static Block dark_metal;
	//glass blocks
	public static Block clear_glass;
	public static Block checked_glass;
	public static Block jail_glass;
	public static Block quartz_glass;
	public static Block pumice_glass;
	public static Block glass_101;
	
 
	public static void init()
	{
		cement = new Cement(Material.SAND).setUnlocalizedName("cement").setCreativeTab(Main.tabDecorativeStylesBlocks);
		concrete = new Concrete(Material.ROCK).setUnlocalizedName("concrete").setCreativeTab(Main.tabDecorativeStylesBlocks);
		concrete_masonry_unit = new ConcreteMasonryUnit(Material.ROCK).setUnlocalizedName("concrete_masonry_unit").setCreativeTab(Main.tabDecorativeStylesBlocks);
		concrete_tiles = new ConcreteTiles(Material.ROCK).setUnlocalizedName("concrete_tiles").setCreativeTab(Main.tabDecorativeStylesBlocks);
		jungle_cobblestone = new JungleCobblestone(Material.ROCK).setUnlocalizedName("jungle_cobblestone").setCreativeTab(Main.tabDecorativeStylesBlocks);
		jungle_mossy_cobblestone = new JungleMossyCobblestone(Material.ROCK).setUnlocalizedName("jungle_mossy_cobblestone").setCreativeTab(Main.tabDecorativeStylesBlocks);
		jungle_stone = new JungleStone(Material.ROCK).setUnlocalizedName("jungle_stone").setCreativeTab(Main.tabDecorativeStylesBlocks);
		jungle_polished_stone = new JunglePolishedStone(Material.ROCK).setUnlocalizedName("jungle_polished_stone").setCreativeTab(Main.tabDecorativeStylesBlocks);
		jungle_stonebrick = new JungleStoneBrick(Material.ROCK).setUnlocalizedName("jungle_stonebrick").setCreativeTab(Main.tabDecorativeStylesBlocks);
		jungle_mossy_stonebrick = new JungleMossyStoneBrick(Material.ROCK).setUnlocalizedName("jungle_mossy_stonebrick").setCreativeTab(Main.tabDecorativeStylesBlocks);
		jungle_stonebrick_cracked = new JungleStoneBrickCracked(Material.ROCK).setUnlocalizedName("jungle_stonebrick_cracked").setCreativeTab(Main.tabDecorativeStylesBlocks);
		jungle_stonebrick_carved = new JungleStoneBrickCarved(Material.ROCK).setUnlocalizedName("jungle_stonebrick_carved").setCreativeTab(Main.tabDecorativeStylesBlocks);
		jungle_brick_block = new JungleBrickBlock(Material.ROCK).setUnlocalizedName("jungle_brick_block").setCreativeTab(Main.tabDecorativeStylesBlocks);
		jungle_purpur_block = new JunglePurpurBlock(Material.ROCK).setUnlocalizedName("jungle_purpur_block").setCreativeTab(Main.tabDecorativeStylesBlocks);
		jungle_concrete_masonry_unit = new JungleConcreteMasonryUnit(Material.ROCK).setUnlocalizedName("jungle_concrete_masonry_unit").setCreativeTab(Main.tabDecorativeStylesBlocks);
		white_cobblestone = new WhiteCobblestone(Material.ROCK).setUnlocalizedName("white_cobblestone").setCreativeTab(Main.tabDecorativeStylesBlocks);
		white_mossy_cobblestone = new WhiteMossyCobblestone(Material.ROCK).setUnlocalizedName("white_mossy_cobblestone").setCreativeTab(Main.tabDecorativeStylesBlocks);
		white_stone = new WhiteStone(Material.ROCK).setUnlocalizedName("white_stone").setCreativeTab(Main.tabDecorativeStylesBlocks);
		white_polished_stone = new WhitePolishedStone(Material.ROCK).setUnlocalizedName("white_polished_stone").setCreativeTab(Main.tabDecorativeStylesBlocks);
		white_stonebrick = new WhiteStoneBrick(Material.ROCK).setUnlocalizedName("white_stonebrick").setCreativeTab(Main.tabDecorativeStylesBlocks);
		white_mossy_stonebrick = new WhiteMossyStoneBrick(Material.ROCK).setUnlocalizedName("white_mossy_stonebrick").setCreativeTab(Main.tabDecorativeStylesBlocks);
		white_stonebrick_cracked = new WhiteStoneBrickCracked(Material.ROCK).setUnlocalizedName("white_stonebrick_cracked").setCreativeTab(Main.tabDecorativeStylesBlocks);
		white_stonebrick_carved = new WhiteStoneBrickCarved(Material.ROCK).setUnlocalizedName("white_stonebrick_carved").setCreativeTab(Main.tabDecorativeStylesBlocks);
		white_brick_block = new WhiteBrickBlock(Material.ROCK).setUnlocalizedName("white_brick_block").setCreativeTab(Main.tabDecorativeStylesBlocks);
		white_purpur_block = new WhitePurpurBlock(Material.ROCK).setUnlocalizedName("white_purpur_block").setCreativeTab(Main.tabDecorativeStylesBlocks);
		white_concrete_masonry_unit = new WhiteConcreteMasonryUnit(Material.ROCK).setUnlocalizedName("white_concrete_masonry_unit").setCreativeTab(Main.tabDecorativeStylesBlocks);
		snow_cobblestone = new SnowCobblestone(Material.ROCK).setUnlocalizedName("snow_cobblestone").setCreativeTab(Main.tabDecorativeStylesBlocks);
		snow_mossy_cobblestone = new SnowMossyCobblestone(Material.ROCK).setUnlocalizedName("snow_mossy_cobblestone").setCreativeTab(Main.tabDecorativeStylesBlocks);
		snow_stone = new SnowStone(Material.ROCK).setUnlocalizedName("snow_stone").setCreativeTab(Main.tabDecorativeStylesBlocks);
		snow_polished_stone = new SnowPolishedStone(Material.ROCK).setUnlocalizedName("snow_polished_stone").setCreativeTab(Main.tabDecorativeStylesBlocks);
		snow_stonebrick = new SnowStoneBrick(Material.ROCK).setUnlocalizedName("snow_stonebrick").setCreativeTab(Main.tabDecorativeStylesBlocks);
		snow_mossy_stonebrick = new SnowMossyStoneBrick(Material.ROCK).setUnlocalizedName("snow_mossy_stonebrick").setCreativeTab(Main.tabDecorativeStylesBlocks);
		snow_stonebrick_cracked = new SnowStoneBrickCracked(Material.ROCK).setUnlocalizedName("snow_stonebrick_cracked").setCreativeTab(Main.tabDecorativeStylesBlocks);
		snow_stonebrick_carved = new SnowStoneBrickCarved(Material.ROCK).setUnlocalizedName("snow_stonebrick_carved").setCreativeTab(Main.tabDecorativeStylesBlocks);
		snow_brick_block = new SnowBrickBlock(Material.ROCK).setUnlocalizedName("snow_brick_block").setCreativeTab(Main.tabDecorativeStylesBlocks);
		snow_purpur_block = new SnowPurpurBlock(Material.ROCK).setUnlocalizedName("snow_purpur_block").setCreativeTab(Main.tabDecorativeStylesBlocks);
		snow_concrete_masonry_unit = new SnowConcreteMasonryUnit(Material.ROCK).setUnlocalizedName("snow_concrete_masonry_unit").setCreativeTab(Main.tabDecorativeStylesBlocks);
		pumice = new Pumice(Material.ROCK).setUnlocalizedName("pumice").setCreativeTab(Main.tabDecorativeStylesBlocks);
		polished_pumice = new PolishedPumice(Material.ROCK).setUnlocalizedName("polished_pumice").setCreativeTab(Main.tabDecorativeStylesBlocks);
		pumice_stonebrick = new PumiceStoneBrick(Material.ROCK).setUnlocalizedName("pumice_stonebrick").setCreativeTab(Main.tabDecorativeStylesBlocks);
		pumice_mossy_stonebrick = new PumiceMossyStoneBrick(Material.ROCK).setUnlocalizedName("pumice_mossy_stonebrick").setCreativeTab(Main.tabDecorativeStylesBlocks);
		pumice_stonebrick_cracked = new PumiceStoneBrickCracked(Material.ROCK).setUnlocalizedName("pumice_stonebrick_cracked").setCreativeTab(Main.tabDecorativeStylesBlocks);
		pumice_stonebrick_carved = new PumiceStoneBrickCarved(Material.ROCK).setUnlocalizedName("pumice_stonebrick_carved").setCreativeTab(Main.tabDecorativeStylesBlocks);
		pumice_brick_block = new PumiceBrickBlock(Material.ROCK).setUnlocalizedName("pumice_brick_block").setCreativeTab(Main.tabDecorativeStylesBlocks);
		pumice_purpur_block = new PumicePurpurBlock(Material.ROCK).setUnlocalizedName("pumice_purpur_block").setCreativeTab(Main.tabDecorativeStylesBlocks);
		pumice_masonry_unit = new PumiceMasonryUnit(Material.ROCK).setUnlocalizedName("pumice_masonry_unit").setCreativeTab(Main.tabDecorativeStylesBlocks);
		carved_stone_1 = new CarvedStone1(Material.ROCK).setUnlocalizedName("carved_stone_1").setCreativeTab(Main.tabDecorativeStylesBlocks);
		carved_stone_2 = new CarvedStone2(Material.ROCK).setUnlocalizedName("carved_stone_2").setCreativeTab(Main.tabDecorativeStylesBlocks);
		carved_stone_3 = new CarvedStone3(Material.ROCK).setUnlocalizedName("carved_stone_3").setCreativeTab(Main.tabDecorativeStylesBlocks);
		oak_wood_parquet = new OakWoodParquet(Material.WOOD).setUnlocalizedName("oak_wood_parquet").setCreativeTab(Main.tabDecorativeStylesBlocks);
		birch_wood_parquet = new BirchWoodParquet(Material.WOOD).setUnlocalizedName("birch_wood_parquet").setCreativeTab(Main.tabDecorativeStylesBlocks);
		spruce_wood_parquet = new SpruceWoodParquet(Material.WOOD).setUnlocalizedName("spruce_wood_parquet").setCreativeTab(Main.tabDecorativeStylesBlocks);
		jungle_wood_parquet = new JungleWoodParquet(Material.WOOD).setUnlocalizedName("jungle_wood_parquet").setCreativeTab(Main.tabDecorativeStylesBlocks);
		acacia_wood_parquet = new AcaciaWoodParquet(Material.WOOD).setUnlocalizedName("acacia_wood_parquet").setCreativeTab(Main.tabDecorativeStylesBlocks);
		darkoak_wood_parquet = new DarkoakWoodParquet(Material.WOOD).setUnlocalizedName("darkoak_wood_parquet").setCreativeTab(Main.tabDecorativeStylesBlocks);
		rusty_block = new RustyBlock(Material.ROCK).setUnlocalizedName("rusty_block").setCreativeTab(Main.tabDecorativeStylesBlocks);
		dark_metal = new DarkMetal(Material.IRON).setUnlocalizedName("dark_metal").setCreativeTab(Main.tabDecorativeStylesBlocks);
		clear_glass = new ClearGlass(Material.GLASS, false).setUnlocalizedName("clear_glass").setCreativeTab(Main.tabDecorativeStylesBlocks);
		checked_glass = new CheckedGlass(Material.GLASS, false).setUnlocalizedName("checked_glass").setCreativeTab(Main.tabDecorativeStylesBlocks);
		jail_glass = new JailGlass(Material.GLASS, false).setUnlocalizedName("jail_glass").setCreativeTab(Main.tabDecorativeStylesBlocks);
		quartz_glass = new QuartzGlass(Material.GLASS, false).setUnlocalizedName("quartz_glass").setCreativeTab(Main.tabDecorativeStylesBlocks);
		pumice_glass = new PumiceGlass(Material.GLASS, false).setUnlocalizedName("pumice_glass").setCreativeTab(Main.tabDecorativeStylesBlocks);
		glass_101 = new Glass101(Material.GLASS, false).setUnlocalizedName("glass_101").setCreativeTab(Main.tabDecorativeStylesBlocks);
	}		

	public static void register()
	{
		GameRegistry.registerBlock(cement, cement.getUnlocalizedName().substring(5));
		GameRegistry.registerBlock(concrete, concrete.getUnlocalizedName().substring(5));
		GameRegistry.registerBlock(concrete_masonry_unit, ItemConcreteMasonryUnit.class, concrete_masonry_unit.getUnlocalizedName().substring(5));
		GameRegistry.registerBlock(concrete_tiles, concrete_tiles.getUnlocalizedName().substring(5));
		GameRegistry.registerBlock(jungle_cobblestone, ItemJungleCobblestone.class, jungle_cobblestone.getUnlocalizedName().substring(5));
		GameRegistry.registerBlock(jungle_mossy_cobblestone, jungle_mossy_cobblestone.getUnlocalizedName().substring(5));
		GameRegistry.registerBlock(jungle_stone, jungle_stone.getUnlocalizedName().substring(5));
		GameRegistry.registerBlock(jungle_polished_stone, jungle_polished_stone.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(jungle_stonebrick, jungle_stonebrick.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(jungle_mossy_stonebrick, jungle_mossy_stonebrick.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(jungle_stonebrick_cracked, jungle_stonebrick_cracked.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(jungle_stonebrick_carved, jungle_stonebrick_carved.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(jungle_brick_block, jungle_brick_block.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(jungle_purpur_block, jungle_purpur_block.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(jungle_concrete_masonry_unit, ItemJungleConcreteMasonryUnit.class, jungle_concrete_masonry_unit.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(white_cobblestone, white_cobblestone.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(white_mossy_cobblestone, white_mossy_cobblestone.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(white_stone, ItemWhiteStone.class, white_stone.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(white_polished_stone, white_polished_stone.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(white_stonebrick, white_stonebrick.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(white_mossy_stonebrick, white_mossy_stonebrick.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(white_stonebrick_cracked, white_stonebrick_cracked.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(white_stonebrick_carved, white_stonebrick_carved.getUnlocalizedName().substring(5)); 
	    GameRegistry.registerBlock(white_brick_block, white_brick_block.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(white_purpur_block, white_purpur_block.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(white_concrete_masonry_unit, ItemWhiteConcreteMasonryUnit.class, white_concrete_masonry_unit.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(snow_cobblestone, snow_cobblestone.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(snow_mossy_cobblestone, snow_mossy_cobblestone.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(snow_stone, snow_stone.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(snow_polished_stone, snow_polished_stone.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(snow_stonebrick, snow_stonebrick.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(snow_mossy_stonebrick, snow_mossy_stonebrick.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(snow_stonebrick_cracked, snow_stonebrick_cracked.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(snow_stonebrick_carved, snow_stonebrick_carved.getUnlocalizedName().substring(5)); 
	    GameRegistry.registerBlock(snow_brick_block, snow_brick_block.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(snow_purpur_block, snow_purpur_block.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(snow_concrete_masonry_unit, ItemSnowConcreteMasonryUnit.class, snow_concrete_masonry_unit.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(pumice, ItemPumice.class, pumice.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(polished_pumice, polished_pumice.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(pumice_stonebrick, pumice_stonebrick.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(pumice_mossy_stonebrick, pumice_mossy_stonebrick.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(pumice_stonebrick_cracked, pumice_stonebrick_cracked.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(pumice_stonebrick_carved, pumice_stonebrick_carved.getUnlocalizedName().substring(5)); 
	    GameRegistry.registerBlock(pumice_brick_block, pumice_brick_block.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(pumice_purpur_block, pumice_purpur_block.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(pumice_masonry_unit, ItemPumiceMasonryUnit.class, pumice_masonry_unit.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(carved_stone_1, carved_stone_1.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(carved_stone_2, carved_stone_2.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(carved_stone_3, carved_stone_3.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(oak_wood_parquet, oak_wood_parquet.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(birch_wood_parquet, birch_wood_parquet.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(spruce_wood_parquet, spruce_wood_parquet.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(jungle_wood_parquet, jungle_wood_parquet.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(acacia_wood_parquet, acacia_wood_parquet.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(darkoak_wood_parquet, darkoak_wood_parquet.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(rusty_block, rusty_block.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(dark_metal, dark_metal.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(clear_glass, ItemClearGlass.class, clear_glass.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(checked_glass, checked_glass.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(jail_glass, jail_glass.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(quartz_glass, quartz_glass.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(pumice_glass, pumice_glass.getUnlocalizedName().substring(5));
	    GameRegistry.registerBlock(glass_101, ItemGlass101.class, glass_101.getUnlocalizedName().substring(5));
	}
	
	public static void registerRenders()
	{
		registerRender(cement);
		registerRender(concrete);
		registerRender(concrete_masonry_unit);
		registerRender(concrete_tiles);
		registerRender(jungle_cobblestone);
		registerRender(jungle_mossy_cobblestone);
		registerRender(jungle_stone);
		registerRender(jungle_polished_stone);
		registerRender(jungle_stonebrick);
		registerRender(jungle_mossy_stonebrick);
		registerRender(jungle_stonebrick_cracked);
		registerRender(jungle_stonebrick_carved);
		registerRender(jungle_brick_block);
		registerRender(jungle_purpur_block);
		registerRender(jungle_concrete_masonry_unit);
		registerRender(white_cobblestone);
		registerRender(white_mossy_cobblestone);
		registerRender(white_stone);
		registerRender(white_polished_stone);
		registerRender(white_stonebrick);
		registerRender(white_mossy_stonebrick);
		registerRender(white_stonebrick_cracked);
		registerRender(white_stonebrick_carved);
		registerRender(white_brick_block);
		registerRender(white_purpur_block);
		registerRender(white_concrete_masonry_unit);
		registerRender(snow_cobblestone);
		registerRender(snow_mossy_cobblestone);
		registerRender(snow_stone);
		registerRender(snow_polished_stone);
		registerRender(snow_stonebrick);
		registerRender(snow_mossy_stonebrick);
		registerRender(snow_stonebrick_cracked);
		registerRender(snow_stonebrick_carved);
		registerRender(snow_brick_block);
		registerRender(snow_purpur_block);
		registerRender(snow_concrete_masonry_unit);
		registerRender(pumice);
		registerRender(polished_pumice);
		registerRender(pumice_stonebrick);
		registerRender(pumice_mossy_stonebrick);
		registerRender(pumice_stonebrick_cracked);
		registerRender(pumice_stonebrick_carved);
		registerRender(pumice_brick_block);
		registerRender(pumice_purpur_block);
		registerRender(pumice_masonry_unit);
		registerRender(carved_stone_1);
		registerRender(carved_stone_2);
		registerRender(carved_stone_3);
		registerRender(oak_wood_parquet);
		registerRender(birch_wood_parquet);
		registerRender(spruce_wood_parquet);
		registerRender(jungle_wood_parquet);
		registerRender(acacia_wood_parquet);
		registerRender(darkoak_wood_parquet);
		registerRender(rusty_block);
		registerRender(dark_metal);
		registerRender(clear_glass);
		registerRender(checked_glass);
		registerRender(jail_glass);
		registerRender(quartz_glass);
		registerRender(pumice_glass);
		registerRender(glass_101);
	}
	
	public static void registerRender(Block block)
	{
		Item item = Item.getItemFromBlock(block);
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(item, 0, new ModelResourceLocation(Reference.MOD_ID + ":" + item.getUnlocalizedName().substring(5), "inventory"));
	}

}	
